### PR TITLE
Add option for primary navigation

### PR DESCRIPTION
**Pull request by seothemes**
See #6.

Also has some coding standards improvements.

### CODE REVIEW

**Comment by marksabbath** [comment]
Hey @seothemes it seems that the newest PHP CS code introduced in the `develop` branch brought some conflicts to this feature.

Would you mind taking a look at them?

**Comment by nathanrice** [comment]
@seothemes I'm just now looking at deploying this, and I'm trying to understand the change made here.

If a person is running version 1.0.1 of this plugin, and updates to 1.1.0 (with these changes), will they lose their currently assigned entry menus? It looks like you've changed the key on the postmeta that gets saved.

I could be missing something, though, so please feel free to fill me in.

**Comment by seothemes** [comment]
@nathanrice I think you are right. Let me have another look.

@marksabbath yep, will check that now.

**Comment by seothemes** [comment]
@nathanrice yes you were correct. I've changed the meta key for the secondary menu back to the original with #14 

@marksabbath I see you already fixed up the coding standards.

**Pull request merged**
